"""Critic training-data composition (app:critic-data): human-only vs all-data critic table.

Reads the critic-data ablation outputs pinned by the ``critic_data`` package
(``sim/critic/data_ablation/``): the per-seed pairs and the per-task Student-t summary. Writes critic_data_table.tex (tab:appendix-critic-data).

Each row is one task, five seeds. Both arms rerank N=32 proposals from the same
frozen seed-matched actor; differences are human-only minus all-data per seed, and
the intervals are two-sided Student-t 95% over the five seed differences. The table
recomputes every mean and interval from the per-seed CSV and requires it to match
the summary.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np
from scipy import stats

from paper.appendix.artifacts import cache_dir, load_inputs, write_json, write_table

HERE = Path(__file__).resolve().parent
CACHE = cache_dir("critic_data")
OUTPUT = "critic_data_table.tex"
TASK_MACROS = {"square_narrow": r"\sqnarrow", "square_broad": r"\sqbroad"}
SEEDS = [1, 2, 3, 4, 5]


def paired_t(d: np.ndarray) -> dict:
    half = stats.t.ppf(0.975, len(d) - 1) * d.std(ddof=1) / np.sqrt(len(d))
    return dict(mean=float(d.mean()), low=float(d.mean() - half), high=float(d.mean() + half))


def rows(inputs: dict[str, Path]) -> list[dict]:
    with inputs["sim/critic/data_ablation/paired_seeds.csv"].open() as handle:
        pairs = list(csv.DictReader(handle))
    summary = json.loads(inputs["sim/critic/data_ablation/summary.json"].read_text())
    out = []
    for task, macro in TASK_MACROS.items():
        seeds = [r for r in pairs if r["task_key"] == task]
        assert sorted(int(r["seed"]) for r in seeds) == SEEDS, task
        col = {
            k: np.array([float(r[k]) for r in seeds])
            for k in seeds[0]
            if k.endswith(("_pct", "_pp"))
        }
        gain_all = col["all_data_n32_pct"] - col["all_data_n1_pct"]
        gain_human = col["human_only_n32_pct"] - col["human_only_n1_pct"]
        row = dict(
            task=task,
            macro=macro,
            all_n32=float(col["all_data_n32_pct"].mean()),
            human_n32=float(col["human_only_n32_pct"].mean()),
            diff_n32=paired_t(col["human_only_n32_pct"] - col["all_data_n32_pct"]),
            diff_n1=paired_t(col["human_only_n1_pct"] - col["all_data_n1_pct"]),
            gain_all=paired_t(gain_all),
            gain_human=paired_t(gain_human),
        )
        s = summary[task]
        for key, ref in (
            ("diff_n32", s["n32"]["human_minus_all"]),
            ("diff_n1", s["n1"]["human_minus_all"]),
            ("gain_all", s["rerank_gain"]["all_data"]),
            ("gain_human", s["rerank_gain"]["human_only"]),
        ):
            got = row[key]
            want = (ref["mean_pp"], ref["t95_low_pp"], ref["t95_high_pp"])
            assert np.allclose((got["mean"], got["low"], got["high"]), want), (task, key)
        assert np.isclose(row["all_n32"], s["n32"]["all_data_mean"]), task
        assert np.isclose(row["human_n32"], s["n32"]["human_only_mean"]), task
        out.append(row)
    return out


def header(*lines: str) -> str:
    """A two-line column header cell."""
    return r"\begin{tabular}[b]{@{}c@{}}" + r" \\ ".join(lines) + r"\end{tabular}"


def interval(t: dict) -> str:
    """Mean over its 95% interval, stacked to keep the table within the text width."""
    return (
        r"\begin{tabular}[t]{@{}r@{}}"
        f"${t['mean']:+.2f}$ \\\\ {{\\scriptsize $[{t['low']:+.2f}, {t['high']:+.2f}]$}}"
        r"\end{tabular}"
    )


def table(cells: list[dict]) -> str:
    columns = (
        "Task",
        header("All-data", r"$N{=}32$"),
        header("Human-only", r"$N{=}32$"),
        header(r"$\Delta$ at", r"$N{=}32$"),
        header(r"$\Delta$ at $N{=}1$", "(same actor)"),
        header("Rerank gain", "all-data"),
        header("Rerank gain", "human-only"),
    )
    lines = [
        "% Generated by paper.appendix.critic_data.prepare.",
        r"\begin{tabular}{lrrrrrr}",
        r"  \hline",
        "  " + " & ".join(columns) + r" \\",
        r"  \hline",
    ]
    for c in cells:
        lines.append(
            f"  {c['macro']} & ${c['all_n32']:.2f}\\%$ & ${c['human_n32']:.2f}\\%$ & "
            f"{interval(c['diff_n32'])} & {interval(c['diff_n1'])} & "
            f"{interval(c['gain_all'])} & {interval(c['gain_human'])} \\\\"
        )
    lines += [r"  \hline", r"\end{tabular}", ""]
    return "\n".join(lines)


def write_tables(check: bool = False) -> Path:
    cells = rows(load_inputs(HERE))
    write_json(
        CACHE / "data/analysis.json",
        dict(schema="mulligan.paper.appendix.critic_data.v1", tasks=cells),
    )
    return write_table(OUTPUT, table(cells), check=check)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Require the manuscript's table body.")
    args = parser.parse_args()
    print(write_tables(check=args.check))


if __name__ == "__main__":
    main()
