"""Recompute existing appendix tables; preserved studies, no new experiments."""

import json

import numpy as np
import pandas as pd

from paper.appendix.artifacts import load_inputs, write_table

from .prepare import CACHE, CONDITIONS, HERE, extract

ARMS = ("idql", "divl-fixed", "divl-adaptive")
SAMPLERS = ("straddled", "balanced_outcome", "flat")


def stats(values):
    values = np.asarray(values, dtype=float)
    assert len(values) > 1 and np.isfinite(values).all()
    return float(values.mean()), float(values.std(ddof=1) / np.sqrt(len(values)))


def extract_tables():
    source = load_inputs(HERE)
    out = CACHE / "data"
    out.mkdir(parents=True, exist_ok=True)
    records = json.loads(source["sim/critic/square_narrow_sampler_runs.json"].read_text())
    narrow = []
    for run in records:
        assert run["sampler"] in SAMPLERS and run["arm"] in ARMS
        assert run["config"]["eval"]["episodes"] == 400
        assert run["config"]["eval"]["fixed_initial_state_seed"] == 20260524
        assert run["summary"]["_step"] >= 150000
        narrow.append(
            dict(
                regime="square_narrow_r1",
                sampler=run["sampler"],
                arm=run["arm"],
                seed=run["seed"],
                success_rate=run["summary"]["eval/success_rate/n32"],
            )
        )
    narrow = pd.DataFrame(narrow)
    assert len(narrow) == 45
    for _, g in narrow.groupby(["sampler", "arm"]):
        assert sorted(g.seed) == [1, 2, 3, 4, 5]
    narrow.to_csv(out / "divl_square_narrow_sampler_seeds.csv", index=False, float_format="%.12g")
    # Square-Broad R15 (seeds 1-3) and R1 (five replicates in reported order, seed identity
    # not recorded) of the scalar-IQL vs DIVL value heads.
    regimes = pd.read_csv(source["sim/critic/divl_regime_replicates.csv"])
    assert set(regimes.arm) == set(ARMS)
    for (regime, _), g in regimes.groupby(["regime", "arm"]):
        n = {"square_broad_r15": 3, "square_broad_r1": 5}[regime]
        assert sorted(g.replicate) == list(range(1, n + 1)), regime
        assert set(g.seed_known) == {regime == "square_broad_r15"}, regime
    regimes.to_csv(out / "divl_other_regime_replicates.csv", index=False, float_format="%.12g")
    capacity_final = pd.read_csv(source["sim/critic/capacity_final_sr.csv"])
    labels = [
        "Actor-depth pred8/exec6",
        "Q-ens 10 REDQ-2 (pred8/exec6)",
        "Q-ens 10 single-critic (pred8/exec6)",
    ]
    redq = capacity_final.loc[
        (capacity_final.task == "Square-Broad")
        & (capacity_final.n == "n32")
        & (capacity_final.step == 300000)
        & capacity_final.label.isin(labels)
    ].copy()
    assert len(redq) == 15
    for _, g in redq.groupby("label"):
        assert sorted(g.seed) == [1, 2, 3, 4, 5]
    redq.to_csv(out / "redq_seeds.csv", index=False, float_format="%.12g")
    frozen = pd.read_csv(source["sim/critic/frozen_actor_results.csv"])
    frozen = frozen.loc[frozen.family == "hil"].copy()
    assert len(frozen) == 170 and frozen.cell_key.nunique() == 34
    assert set(frozen.status) == {"grid_complete"}
    for _, g in frozen.groupby("cell_key"):
        assert sorted(g.seed) == [1, 2, 3, 4, 5]
    assert np.allclose(
        frozen.grid_n32_pct - frozen.parent_grid_n32_pct, frozen.delta_grid_pp, atol=5e-7
    )
    frozen.to_csv(out / "frozen_actor_hil_seeds.csv", index=False, float_format="%.12g")
    means = frozen.groupby("cell_key").delta_grid_pp.mean()
    summary = {
        "n_cells": len(means),
        "n_seeds_per_cell": 5,
        "min_delta_pp": float(means.min()),
        "max_delta_pp": float(means.max()),
        "positive_cells": int((means > 0).sum()),
        "negative_cells": int((means < 0).sum()),
        "equal_cell_mean_delta_pp": float(means.mean()),
    }
    (out / "frozen_actor_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    return narrow, regimes, redq, summary


def _tabular(columns, header, rows):
    return "\n".join(
        [
            "% Generated by paper.appendix.simulation.tables.",
            r"\begin{tabular}{" + columns + "}",
            r"\hline",
            header + r" \\",
            r"\hline",
            *[row + r" \\" for row in rows],
            r"\hline",
            r"\end{tabular}",
            "",
        ]
    )


def write_tables(*, check=False):
    paths = extract()
    narrow, regimes, redq, summary = extract_tables()
    critic = pd.read_csv(paths["critic_objective_seeds.csv"])
    labels = [
        r"Baseline, reward $[0,1]$, clipped targets",
        r"Shifted reward $[-1,0]$, no target clipping",
        r"Intervention frames treated as terminal",
        r"Actor update cadence $4{:}1{:}1$",
        r"Actor update cadence $2{:}1{:}1$",
        r"Flat (uniform) critic sampling",
        r"QC, no $V$-network",
        r"QC $+$ intervention-terminal $+$ cadence $2{:}1$",
        r"QC $+$ shifted reward $[-1,0]$",
    ]
    objective_rows = []
    for (condition, _), label in zip(CONDITIONS, labels, strict=True):
        values = critic.loc[critic.condition == condition, "success_rate"]
        mean, se = stats(values)
        objective_rows.append(f"{label} & {len(values)} & ${mean:.2f} \\pm {se:.2f}$")
    output = {
        "critic_objective_table.tex": _tabular(
            "lcc", r"Condition & Seeds & Final SR (\%)", objective_rows
        )
    }
    regime_rows = []
    for regime, label in [
        ("square_broad_r1", r"Low SR ($\sim70\%$)"),
        ("square_broad_r15", r"High SR ($\sim90\%$)"),
        ("square_narrow_r1", r"High SR ($\sim94\%$)"),
    ]:
        df = (
            narrow.loc[narrow.sampler == "straddled"]
            if regime == "square_narrow_r1"
            else regimes.loc[regimes.regime == regime]
        )
        values = [stats(df.loc[df.arm == arm, "success_rate"]) for arm in ARMS]
        m, se = values[0]
        regime_rows.append(
            f"{label} & ${m:.2f} \\pm {se:.2f}$ & ${values[1][0] - m:+.2f}$ & ${values[2][0] - m:+.2f}$"
        )
    output["divl_regime_table.tex"] = _tabular(
        "lccc",
        r"Regime (scalar-IQL base SR) & scalar IQL & \texttt{divl-fixed} & \texttt{divl-adaptive}",
        regime_rows,
    )
    sampler_rows = []
    for sampler in SAMPLERS:
        df = narrow.loc[narrow.sampler == sampler]
        values = [stats(df.loc[df.arm == arm, "success_rate"]) for arm in ARMS]
        m, se = values[0]
        label = sampler.replace("_", r"\_")
        sampler_rows.append(
            r"\texttt{"
            + label
            + "}"
            + f" & ${m:.2f} \\pm {se:.2f}$ & ${values[1][0]:.2f}$ (${values[1][0] - m:+.2f}$) & ${values[2][0]:.2f}$ (${values[2][0] - m:+.2f}$)"
        )
    output["divl_sampler_table.tex"] = _tabular(
        "lccc",
        r"Critic sampler & scalar IQL (control) & \texttt{divl-fixed} & \texttt{divl-adaptive}",
        sampler_rows,
    )
    redq_rows = []
    baseline = stats(redq.loc[redq.label == "Actor-depth pred8/exec6", "success_rate"])[0]
    for condition, label, n in [
        ("Actor-depth pred8/exec6", r"$2$-$Q$ min", 2),
        ("Q-ens 10 REDQ-2 (pred8/exec6)", "REDQ-2", 10),
        ("Q-ens 10 single-critic (pred8/exec6)", "Single random critic", 10),
    ]:
        m, se = stats(redq.loc[redq.label == condition, "success_rate"])
        delta = "---" if n == 2 else f"${m - baseline:+.2f}$"
        redq_rows.append(f"{label} & ${n}$ & ${m:.2f} \\pm {se:.2f}$ & {delta}")
    output["redq_table.tex"] = _tabular(
        "lccc", r"Critic ensemble & $|$ensemble$|$ & Final $N{=}32$ SR (\%) & $\Delta$", redq_rows
    )
    output.update(sampling_tables())
    paths = []
    for name, text in output.items():
        (CACHE / "data" / name).write_text(text)
        paths.append(write_table(name, text, check=check))
    return paths


def sampling_tables():
    from scipy.stats import t as student_t

    source = load_inputs(HERE)
    data = pd.read_csv(source["sim/critic/frozen_actor_results.csv"])
    data = data.loc[data.family == "hil"]

    def values(key):
        group = data.loc[data.cell_key == key].sort_values("seed")
        assert sorted(group.seed) == [1, 2, 3, 4, 5], key
        return group.grid_n32_pct.to_numpy()

    def contrast(a, b):
        delta = a.mean() - b.mean()
        va = a.var(ddof=1) / len(a)
        vb = b.var(ddof=1) / len(b)
        df = (va + vb) ** 2 / (va**2 / (len(a) - 1) + vb**2 / (len(b) - 1))
        half = student_t.ppf(0.975, df) * np.sqrt(va + vb)
        return float(delta), float(delta - half), float(delta + half)

    configs = [
        (
            "square_narrow_r1_baseline_uniform_no_cf_human_only",
            "Uniform, no-CF, HO (reference)",
        ),
        (
            "square_narrow_r1_baseline_uniform_no_cf_straddled_auto_success",
            "Uniform, no-CF, $+$auto successes",
        ),
        ("square_narrow_r1_sobol_no_cf_human_only", "Sobol coverage, no-CF, HO"),
        ("square_narrow_r1_sobol_with_cf_human_only", "Sobol coverage, with-CF, HO"),
        (
            "square_narrow_r1_mulligan_no_cf_human_only",
            r"Performance-guided ($\beta{=}0.5$), no-CF, HO",
        ),
        (
            "square_narrow_r1_mulligan_with_cf_human_only",
            r"Performance-guided ($\beta{=}0.5$), with-CF, HO",
        ),
    ]
    baseline = values(configs[0][0])
    rows = []
    summaries = []
    for key, label in configs:
        v = values(key)
        mean, se = stats(v)
        delta, lo, hi = contrast(v, baseline)
        ci = "---" if key == configs[0][0] else f"${delta:+.2f}$ $[{lo:+.2f}, {hi:+.2f}]$"
        rows.append(f"{label} & ${mean:.2f} \\pm {se:.2f}$ & {ci}")
        summaries.append(
            dict(cell_key=key, mean=mean, se=se, delta=delta, ci95_low=lo, ci95_high=hi)
        )
    pd.DataFrame(summaries).to_csv(
        CACHE / "data/sampler_ablation_summary.csv", index=False, float_format="%.12g"
    )
    data.loc[data.cell_key.isin([key for key, _ in configs])].to_csv(
        CACHE / "data/sampler_ablation_seeds.csv", index=False, float_format="%.12g"
    )
    r0 = {}
    for task in ("square_narrow", "square_broad"):
        a = values(f"{task}_r0_sobol")
        b = values(f"{task}_r0_baseline_uniform")
        r0[task] = dict(
            baseline_mean=stats(b)[0],
            baseline_se=stats(b)[1],
            sobol_mean=stats(a)[0],
            sobol_se=stats(a)[1],
            contrast=contrast(a, b),
        )
    sequence = [
        stats(values(key))[0]
        for key in (
            "square_narrow_r0_sobol",
            "square_narrow_r1_mulligan_with_cf_human_only",
            "square_narrow_r2_mulligan_with_cf_human_only",
            "square_narrow_r3_mulligan_with_cf_human_only",
        )
    ]
    (CACHE / "data/sampler_narrative_audit.json").write_text(
        json.dumps({"round0": r0, "narrow_sequence": sequence}, indent=2) + "\n"
    )
    return {
        "sampler_ablation_table.tex": _tabular(
            "lcc", r"Collection strategy / actor data & Grid SR (\%) & $\Delta$ [$95\%$ CI]", rows
        )
    }
