#!/usr/bin/env python3
"""
Data collection and dataset constants.

This module defines constants used across teleoperation, DAgger data collection,
and training pipelines to ensure consistency.
"""

from enum import IntEnum


class DataSource(IntEnum):
    """
    Source of a transition/action in a dataset.

    Used to distinguish between human-generated and autonomously-generated data
    in datasets that mix teleoperation, corrections, and policy rollouts.

    Values:
        AUTONOMOUS: Action generated by autonomous policy
        HUMAN: Action generated by human teleoperator (demo or correction)
    """

    AUTONOMOUS = 0
    HUMAN = 1


class EpisodeOutcome(IntEnum):
    """
    Outcome/success status of an episode.

    Values:
        FAILURE: Episode failed (task not completed, irrecoverable error, etc.)
        SUCCESS: Episode succeeded (task completed successfully)
    """

    FAILURE = 0
    SUCCESS = 1
