"""Per-state success counts drawn by the teaser's bucket chart (``assets/bucket_counts.js``).

The 80 counts are the documented digitization of the archived Square-Narrow R2 bucket
raster (``simulation`` evidence), not original rollout logs.
"""

import json

import pandas as pd

from paper.appendix.artifacts import sha256
from paper.appendix.simulation.prepare import HERE as SIMULATION
from paper.appendix.simulation.prepare import extract

from .prepare import CACHE


def bucket_counts_js() -> str:
    """The teaser's ``bucket_counts.js`` body, rebuilt from the pinned digitization."""
    frame = pd.read_csv(extract()["bucket_counts.csv"])
    assert frame["rank"].tolist() == list(range(1, 81))
    assert set(frame.rollouts) == {50}
    (CACHE / "data").mkdir(parents=True, exist_ok=True)
    frame.to_csv(CACHE / "data/teaser_bucket_counts.csv", index=False)
    counts = frame.successes.astype(int).tolist()
    assert counts == sorted(counts) and sum(counts) == 3438
    assert sum(50 - count for count in counts[:20]) == 533
    return (
        "// Generated by paper.appendix.productivity.teaser.\n"
        "// Evidence: recovered counts from the archived raster, not original rollout logs.\n"
        f"// Input lock: paper/appendix/simulation/inputs.json sha256={sha256(SIMULATION / 'inputs.json')}\n"
        f"const bucketCounts = {json.dumps(counts)};\n"
        "const bucketRollouts = 50;\n"
    )


def main() -> None:
    print(bucket_counts_js(), end="")


if __name__ == "__main__":
    main()
