"""Per-round Welch-t contrasts for the two simulation campaigns (tab:appendix-sim-significance).

Actor-only (N = 1) arms come from the frozen per-seed held-out success rates behind the
simulation headline (``paper/data/sim/sim_significance/partial_headline.csv``);
critic-reranked (N = 32) arms come from the DIVL frozen-actor campaign that the paper's
N = 32 simulation numbers use (``paper/data/sim/sim_significance/divl_frozen_actor_results.csv``,
column ``grid_n32_pct``). Five training seeds per arm and round; held-out grids of 8,000
(Square-Narrow) and 30,000 (Square-Broad) episodes per seed.

    python -m paper.stats.sim_welch_table [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

from mulligan.plotting.paper import BUILD_DIR, POLICY_ARM_LABELS
from mulligan.sim.task_names import sim_task_display_name
from paper.stats.sim_contrasts import divl_cells, welch

DATA = Path(__file__).resolve().parents[1] / "data/sim"
SRC = DATA / "sim_significance/partial_headline.csv"
NAME = "sim_significance_table.tex"
HEADER = "% Generated by paper.stats.sim_welch_table."
# headline lineage cells of the DIVL campaign, per task and round: (baseline cell, ours cell)
N32_CELLS = {
    ("square_narrow", 0): ("square_narrow_r0_baseline_uniform", "square_narrow_r0_sobol"),
    ("square_narrow", 1): (
        "square_narrow_r1_baseline_uniform_no_cf_human_only",
        "square_narrow_r1_mulligan_with_cf_human_only",
    ),
    ("square_narrow", 2): (
        "square_narrow_r2_baseline_uniform_no_cf_human_only",
        "square_narrow_r2_mulligan_with_cf_human_only",
    ),
    ("square_narrow", 3): (
        "square_narrow_r3_baseline_uniform_no_cf_human_only_with_c03_rollouts",
        "square_narrow_r3_mulligan_with_cf_human_only",
    ),
    ("square_broad", 0): ("square_broad_r0_baseline_uniform", "square_broad_r0_sobol"),
    ("square_broad", 1): (
        "square_broad_r1_baseline_uniform_no_cf_human_only",
        "square_broad_r1_mulligan_with_cf_human_only",
    ),
    ("square_broad", 2): (
        "square_broad_r2_baseline_uniform_no_cf_human_only",
        "square_broad_r2_mulligan_with_cf_human_only",
    ),
    ("square_broad", 3): (
        "square_broad_r3_baseline_uniform_no_cf_human_only",
        "square_broad_r3_mulligan_with_cf_human_only",
    ),
}
TASKS = [("square_narrow", "\\sqnarrow"), ("square_broad", "\\sqbroad")]
# Paper arm name of each series (same register as paper/appendix/simulation/plot.py).
SERIES_LABELS = {
    "human_baseline_n1": POLICY_ARM_LABELS["baseline"],
    "mulligan_n1": POLICY_ARM_LABELS["mulligan_with_cf"],
    "human_baseline_n32": POLICY_ARM_LABELS["baseline_bon"],
    "mulligan_n32": POLICY_ARM_LABELS["final_iql"],
}
CONTRASTS = [
    ("HG-DAgger+\\ours{} vs.\\ HG-DAgger", "mulligan_n1", "human_baseline_n1"),
    ("HiL-IDQL+\\ours{} vs.\\ HiL-IDQL", "mulligan_n32", "human_baseline_n32"),
    ("HiL-IDQL+\\ours{} vs.\\ HG-DAgger", "mulligan_n32", "human_baseline_n1"),
]


def fmt_signed(v):
    return f"{v:+.1f}" if abs(v) >= 0.05 else "0.0"


def seed_rates() -> dict[tuple[str, int, str], list[float]]:
    """Per-seed success rates keyed by (task, round, series)."""
    with SRC.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    # autonomous arms branch at R1, so they may have no R0 rows
    assert len(rows) in (280, 320), len(rows)
    sr = defaultdict(list)
    for r in rows:
        assert r["point_status"] == "complete"
        sr[(r["task_key"], int(r["round"]), r["series_key"])].append(float(r["overall_sr"]))
    # replace the N = 32 arms with the DIVL frozen-actor campaign cells
    cells = divl_cells()
    for (task, rnd), (b_cell, o_cell) in N32_CELLS.items():
        sr[(task, rnd, "human_baseline_n32")] = list(cells[b_cell])
        sr[(task, rnd, "mulligan_n32")] = list(cells[o_cell])
    for k, v in sr.items():
        assert len(v) == 5, (k, len(v))
    for task, _ in TASKS:
        for _, a_key, b_key in CONTRASTS:
            for rnd in range(4):
                assert (task, rnd, a_key) in sr and (task, rnd, b_key) in sr, (task, rnd)
    return sr


def render(sr) -> str:
    lines = [
        HEADER,
        # Each cell stacks the difference with its interval over the p-value, and each
        # contrast label stacks its two arms, so the table fits the 5.5in text width.
        "\\begin{tabular}{lcccc}",
        "\\hline",
        "Contrast & R0 & R1 & R2 & R3 \\\\",
        "\\hline",
    ]
    for task, label in TASKS:
        lines.append(f"\\multicolumn{{5}}{{l}}{{\\textit{{{label}}}}} \\\\")
        for name, a_key, b_key in CONTRASTS:
            cells = []
            for rnd in range(4):
                d, lo, hi, p = welch(sr[(task, rnd, a_key)], sr[(task, rnd, b_key)])
                ptxt = f"\\mathbf{{p = {p:.3f}}}" if p < 0.05 else f"p = {p:.2f}"
                if p < 0.001:
                    ptxt = "\\mathbf{p < 0.001}"
                cells.append(
                    f"\\shortstack{{${fmt_signed(d)}$ $[{fmt_signed(lo)}, {fmt_signed(hi)}]$"
                    f"\\\\${ptxt}$}}"
                )
            a_label, b_label = name.split(" vs.\\ ")
            lines.append(
                f"\\shortstack[l]{{{a_label}\\\\vs.\\ {b_label}}} & " + " & ".join(cells) + " \\\\"
            )
        lines.append("\\hline")
    lines += ["\\end{tabular}", ""]
    return "\n".join(lines)


def build(out_dir: Path) -> Path:
    out = Path(out_dir) / NAME
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(seed_rates()))
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", type=Path, default=BUILD_DIR / "tables")
    out = build(parser.parse_args().out_dir)
    sr = seed_rates()
    # per-round means for the prose
    for task, _ in TASKS:
        for key in ("human_baseline_n1", "mulligan_n1", "human_baseline_n32", "mulligan_n32"):
            print(
                f"{task} ({sim_task_display_name(task)})",
                f"{key} ({SERIES_LABELS[key]})",
                [f"{np.mean(sr[(task, r, key)]):.2f}" for r in range(4)],
            )
    print("wrote", out)


if __name__ == "__main__":
    main()
