"""Rebuild appendix reference tables from the pinned source records.

Run with ``python -m paper.appendix.reference_data.prepare``. This package reads only the
pinned paper evidence; it queries no experiment service, HF, or label database. Authored
(hand-written) tables are not regenerated: their bodies are the frozen manuscript's
(``paper/reference/tables/authored``), each pinned by sha256 in ``inventory.json``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import t

from mulligan.plotting import paper
from paper.appendix.artifacts import (
    REFERENCE_TABLES,
    TABLES_DIR,
    cache_dir,
    load_inputs,
    sha256,
    write_json,
    write_table,
)

HERE = Path(__file__).resolve().parent
CACHE = cache_dir("reference_data")
COHORTS = (
    ("square_narrow_r2_mulligan_with_cf_human_only", r"\sqnarrow R2"),
    ("square_narrow_r3_mulligan_with_cf_human_only", r"\sqnarrow R3"),
    ("square_broad_r3_mulligan_with_cf_all_data", r"\sqbroad R3"),
)
ASSETS = (
    "overview_funnel.pdf",
    "real_world_marker_d2_teleop_card.png",
    "real_world_square_d2_teleop_card.png",
    "real_world_routing_d2_teleop_card.png",
)


def table(columns: str, header: str, rows: list[str]) -> str:
    return (
        "% Generated by paper.appendix.reference_data.prepare.\n"
        + r"\begin{tabular}{"
        + columns
        + "}\n  \\hline\n  "
        + header
        + " \\\\\n  \\hline\n  "
        + "\n  ".join(rows)
        + "\n  \\hline\n\\end{tabular}\n"
    )


def build_tables(inputs: dict[str, Path]) -> tuple[dict[str, str], dict]:
    runs = pd.read_csv(inputs["sim/results/recap/runs.csv"])
    summary = json.loads(inputs["sim/results/recap/summary.json"].read_text())["comparisons"]
    rows, recap_results = [], []
    for key, label in COHORTS:
        selected = runs[runs.comparison_key == key]
        assert len(selected) == 10 and not selected.duplicated(["learner", "seed"]).any()
        assert set(selected.learner) == {"dp_iql", "recap"}
        # Only the held-out grid is reported, not the 400-start training readout.
        readout = "grid"
        assert (selected[f"{readout}_status"] == "ok").all()
        paired = selected.pivot(index="seed", columns="learner", values=f"{readout}_sr")
        assert list(paired.index) == [1, 2, 3, 4, 5]
        assert np.isfinite(paired.to_numpy()).all()
        assert ((paired >= 0) & (paired <= 100)).all().all()
        means, ses = paired.mean(), paired.std(ddof=1) / np.sqrt(5)
        delta = paired.recap - paired.dp_iql
        mean, se = float(delta.mean()), float(delta.std(ddof=1) / np.sqrt(5))
        low, high = mean - t.ppf(0.975, 4) * se, mean + t.ppf(0.975, 4) * se
        for learner in ("dp_iql", "recap"):
            expected = summary[key]["learners"][learner][readout]
            assert expected["n"] == 5
            np.testing.assert_allclose(
                [means[learner], ses[learner]], [expected["mean"], expected["se"]], atol=1e-10
            )
        expected_delta = summary[key]["pairwise_deltas"]["recap_minus_dp_iql"][readout]
        np.testing.assert_allclose(
            [mean, se], [expected_delta["mean"], expected_delta["se"]], atol=1e-10
        )
        rows.append(
            f"{label} & ${means.dp_iql:.2f} \\pm {ses.dp_iql:.2f}$ & "
            f"${means.recap:.2f} \\pm {ses.recap:.2f}$ & ${mean:.2f}$ & $[{low:.2f}, {high:.2f}]$ "
            + r"\\"
        )
        recap_results.append(
            dict(
                cohort=key,
                readout=readout,
                n=5,
                delta_pp=mean,
                paired_ci95_pp=[float(low), float(high)],
            )
        )

    outputs = {
        "reference_recap.tex": table(
            r"lccr@{\hskip 6pt}c",
            r"Cohort & DP$+$IQL & RECAP & \multicolumn{1}{c}{$\Delta$ (pp)} & Paired $95\%$ CI",
            rows,
        )
    }
    coverage = pd.read_csv(inputs["real/collection/stage_census/coverage_by_repo.csv"])
    counts = {
        (row["dataset"], row["part"]): row["episodes"]
        for row in json.loads(
            inputs["real/collection/stage_census/episode_counts.json"].read_text()
        )
    }
    assert len(coverage) == 36 and not coverage.duplicated(["dataset", "part"]).any()
    assert set(zip(coverage.dataset, coverage.part)) == set(counts)
    assert set(coverage.line) == {
        "marker_d2",
        "square_d2",
        "routing_d2",
        "square_fixed_peg",
        "insert_marker_d1",
    }
    for row in coverage.itertuples():
        assert row.total_episodes == counts[(row.dataset, row.part)]
        assert row.n_vlm == row.n_both + row.n_vlm_only
        assert row.n_human == row.n_both + row.n_human_only
        assert (
            row.total_episodes == row.n_both + row.n_vlm_only + row.n_human_only + row.n_unlabeled
        )
    totals = coverage.groupby("line").agg(
        repos=("dataset", "size"),
        episodes=("total_episodes", "sum"),
        vlm=("n_vlm", "sum"),
        human=("n_human", "sum"),
        both=("n_both", "sum"),
    )

    assert totals.sum().to_dict() == {
        "repos": 36,
        "episodes": 4793,
        "vlm": 4325,
        "human": 516,
        "both": 503,
    }
    report = dict(
        schema="mulligan.paper.appendix.reference_data.analysis.v1",
        census_scope="36 repositories in the stage-label census; not complete campaign totals",
        coverage=totals.astype(int).to_dict(orient="index"),
        recap=recap_results,
    )
    return outputs, report


def authored_tables() -> list[Path]:
    """Write each frozen authored table body to ``tables/authored/``.

    Every body must match its sha256 in ``inventory.json``. This detects drift of the
    frozen copy, not experimental or literature correctness.
    """
    inventory = json.loads((HERE / "inventory.json").read_text())
    paths = []
    for item in inventory["authored_tables"]:
        name = item["label"].removeprefix("tab:") + ".tex"
        body = (REFERENCE_TABLES / "authored" / name).read_bytes()
        if hashlib.sha256(body).hexdigest() != item["sha256"]:
            raise AssertionError(f"authored table differs from its pin: {item['label']}")
        path = TABLES_DIR / "authored" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
        paths.append(path)
    return paths


def materialize_assets(*, check: bool = False) -> list[Path]:
    """Restore pinned author-approved exports; no typography conversion or resampling."""
    inputs = load_inputs(HERE)
    targets = {paper.FIGS_DIR / name: inputs["assets/illustrations/" + name] for name in ASSETS}
    for target, source in targets.items():
        if check:
            if sha256(target) != sha256(source):
                raise AssertionError(f"{target} differs from its archived export")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
    return list(targets)


def build(check: bool = False) -> list[Path]:
    inputs = load_inputs(HERE)
    outputs, report = build_tables(inputs)
    write_json(CACHE / "data/analysis.json", report)
    paths = [write_table(name, content, check=check) for name, content in outputs.items()]
    return paths + authored_tables()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Require the manuscript's table bodies."
    )
    parser.add_argument("--restore-assets", action="store_true")
    args = parser.parse_args()
    paths = build(check=args.check)
    if args.restore_assets:
        paths.extend(materialize_assets())
    for path in paths:
        print(path)


if __name__ == "__main__":
    main()
