"""Summarize the frozen-actor DIVL comparison (tab:appendix-divl-frozen) from the pinned ledger.

All changes are percentage points, computed within each matched cell/seed first. The
per-cell summary must reproduce the frozen ``divl_comparison_cells.csv`` byte for byte.

    python -m paper.appendix.paper_side.divl_comparison [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import math
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev

from mulligan.plotting.paper import BUILD_DIR
from mulligan.sim.task_names import sim_task_display_name

DATA = Path(__file__).resolve().parents[2] / "data/sim/sim_significance"
SOURCE = DATA / "divl_frozen_actor_results.csv"
SOURCE_SHA256 = "1fd772be9de0f11b710cb8c96b4103ea0b9e0dee47dae522ce34c61db160e926"
CELLS = DATA / "divl_comparison_cells.csv"
NAME = "divl_frozen_actor_table.tex"
HEADER = "% Generated by paper.appendix.paper_side.divl_comparison."


def comparison_cells() -> list[dict]:
    assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == SOURCE_SHA256
    with SOURCE.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    assert len(rows) == 230
    assert len({(row["cell_key"], row["seed"]) for row in rows}) == 230
    groups = defaultdict(list)
    for row in rows:
        assert row["status"] == "grid_complete"
        assert row["checkpoint"] and row["parent_checkpoint"]
        old, new, delta = map(
            float, (row["parent_grid_n32_pct"], row["grid_n32_pct"], row["delta_grid_pp"])
        )
        assert all(math.isfinite(value) for value in (old, new, delta))
        assert 0 <= old <= 100 and 0 <= new <= 100
        assert math.isclose(new - old, delta, abs_tol=1e-5)
        groups[row["cell_key"]].append(row)
    assert len(groups) == 46
    cells = []
    for key, group in sorted(groups.items()):
        assert {int(row["seed"]) for row in group} == {1, 2, 3, 4, 5}
        assert (
            len({(row["family"], row["task_key"], row["stage"], row["arm"]) for row in group}) == 1
        )
        if group[0]["family"] != "hil":
            assert group[0]["family"] == "autonomous_iql"
            continue
        old = [float(row["parent_grid_n32_pct"]) for row in group]
        new = [float(row["grid_n32_pct"]) for row in group]
        delta = [b - a for a, b in zip(old, new, strict=True)]
        cells.append(
            dict(
                cell_key=key,
                task_key=group[0]["task_key"],
                n_seeds=5,
                scalar_sr_mean=mean(old),
                divl_sr_mean=mean(new),
                delta_pp_mean=mean(delta),
                delta_pp_se=stdev(delta) / math.sqrt(5),
            )
        )
    assert len(cells) == 34
    assert sum(cell["task_key"] == "square_narrow" for cell in cells) == 16
    assert sum(cell["task_key"] == "square_broad" for cell in cells) == 18
    stream = io.StringIO()
    writer = csv.DictWriter(stream, fieldnames=list(cells[0]), lineterminator="\n")
    writer.writeheader()
    writer.writerows(cells)
    if stream.getvalue() != CELLS.read_text():
        raise AssertionError(f"recomputed cell summary differs from {CELLS}")
    return cells


def summary(cells: list[dict]) -> list[tuple[str, str, list[float]]]:
    """Per-task (and pooled) cell-mean DIVL-minus-scalar deltas."""
    return [
        (task, label, [c["delta_pp_mean"] for c in cells if task == "all" or c["task_key"] == task])
        for task, label in (
            ("square_narrow", r"\sqnarrow"),
            ("square_broad", r"\sqbroad"),
            ("all", "Both tasks"),
        )
    ]


def render(cells: list[dict]) -> str:
    lines = [
        HEADER,
        r"\begin{tabular}{lrrrr}",
        r"\hline",
        r"Task & Cells & Mean $\Delta$ (pp) & Cell range (pp) & Cells favoring DIVL / scalar \\",
        r"\hline",
    ]
    for _, label, delta in summary(cells):
        positive = sum(value > 0 for value in delta)
        negative = sum(value < 0 for value in delta)
        lines.append(
            f"{label} & ${len(delta)}$ & ${mean(delta):+.2f}$ & "
            f"$[{min(delta):+.2f}, {max(delta):+.2f}]$ & ${positive}$ / ${negative}$" + r" \\",
        )
    lines += [r"\hline", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build(out_dir: Path) -> Path:
    out = Path(out_dir) / NAME
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(comparison_cells()))
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", type=Path, default=BUILD_DIR / "tables")
    out = build(parser.parse_args().out_dir)
    for task, _, delta in summary(comparison_cells()):
        positive = sum(value > 0 for value in delta)
        negative = sum(value < 0 for value in delta)
        name = "both tasks" if task == "all" else sim_task_display_name(task)
        print(
            f"{task} ({name}): {len(delta)} cells; mean {mean(delta):+.6f} pp; "
            f"range [{min(delta):+.6f}, {max(delta):+.6f}]; signs {positive}/{negative}"
        )
    print("wrote", out)


if __name__ == "__main__":
    main()
