"""Registered-run compute table (tab:training-compute) from the frozen W&B run extract.

Reads ``paper/data/sim/training_compute/records.json`` (the run metadata of the
386 registered paper runs) and re-derives the frozen ``runs.csv`` and ``summary.json`` next to them, which
must match byte for byte.

    python -m paper.appendix.paper_side.training_compute [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from statistics import median

from mulligan.plotting.paper import BUILD_DIR

DATA = Path(__file__).resolve().parents[2] / "data/sim/training_compute"
NAME = "training_compute.tex"
HEADER = "% Generated by paper.appendix.paper_side.training_compute."
TASKS = {
    "square_narrow": r"\sqnarrow",
    "square_broad": r"\sqbroad",
    "marker_d2": r"\marker",
    "square_d2": r"\nut",
    "routing_d2": r"\cable",
}
ROLES = {
    "actor_and_scalar_critic": "Actor + scalar critic",
    "divl_critic": "DIVL critic",
    "actor": "Actor",
    "critic": "Critic",
}


def gpu_count(row):
    hardware = row["hardware"]
    if "gpu_count" in hardware:
        count = int(hardware["gpu_count"])
        source = "W&B GPU metadata"
    else:
        count = int(hardware["slurm"]["gpus_on_node"]) * int(hardware["slurm"]["job_num_nodes"])
        source = "W&B archived SLURM allocation"
    assert count == 1, (row["run"], count)
    return count, source


def compute() -> tuple[str, dict]:
    """Return the table body and the summary; check both frozen derived files."""
    records = json.loads((DATA / "records.json").read_text())
    assert len(records) == len({r["run"] for r in records}) == 386
    groups = defaultdict(list)
    hardware_groups = defaultdict(list)
    runs = []
    for r in records:
        assert r["state"] == "finished", r["run"]
        seconds = r["runtime_seconds"]
        assert math.isfinite(seconds) and seconds > 0, r["run"]
        count, count_source = gpu_count(r)
        hours = seconds / 3600
        run = dict(
            task=r["task"],
            role=r["role"],
            run=r["run"],
            gpu=r["hardware"].get("gpu", "Model not recorded"),
            gpu_count=count,
            gpu_count_source=count_source,
            logged_wall_hours=hours,
            gpu_weighted_logged_hours=count * hours,
            restart_count=r["hardware"]["slurm"].get("restart_count", "not_recorded"),
        )
        runs.append(run)
        groups[(r["task"], r["role"])].append(run)
        hardware_groups[run["gpu"]].append(run)
    assert Counter(r["task"] for r in runs) == dict(
        square_narrow=160, square_broad=180, marker_d2=16, square_d2=15, routing_d2=15
    )
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=list(runs[0]))
    writer.writeheader()
    writer.writerows(runs)
    if stream.getvalue().encode() != (DATA / "runs.csv").read_bytes():
        raise AssertionError(f"recomputed runs differ from {DATA / 'runs.csv'}")
    body = [
        HEADER,
        r"\begin{tabular}{llrrrr}",
        r"\hline",
        r"Task & Fit & Runs & Median h & Range h & Sum GPU-h \\",
        r"\hline",
    ]
    summaries = []
    for (task, role), rows in groups.items():
        hours = [r["logged_wall_hours"] for r in rows]
        total = sum(r["gpu_weighted_logged_hours"] for r in rows)
        summaries.append(
            dict(
                task=task,
                role=role,
                runs=len(rows),
                median_wall_hours=median(hours),
                min_wall_hours=min(hours),
                max_wall_hours=max(hours),
                gpu_weighted_logged_hours=total,
            )
        )
        body.append(
            f"{TASKS[task]} & {ROLES[role]} & {len(rows)} & {median(hours):.2f} & "
            f"{min(hours):.2f}--{max(hours):.2f} & {total:.1f}" + r" \\"
        )
    total = sum(r["gpu_weighted_logged_hours"] for r in runs)
    body.extend(
        [r"\hline", f"Total & & {len(runs)} & & & {total:.1f} \\\\", r"\hline", r"\end{tabular}"]
    )
    summary = dict(
        runs=len(runs),
        gpu_weighted_logged_hours=total,
        recorded_restarts=sum(
            r["restart_count"] != "not_recorded" and int(r["restart_count"]) > 0 for r in runs
        ),
        groups=summaries,
        gpu_models={
            gpu: dict(
                runs=len(rows),
                gpu_weighted_logged_hours=sum(r["gpu_weighted_logged_hours"] for r in rows),
            )
            for gpu, rows in sorted(hardware_groups.items())
        },
    )
    if json.dumps(summary, indent=2) + "\n" != (DATA / "summary.json").read_text():
        raise AssertionError(f"recomputed summary differs from {DATA / 'summary.json'}")
    return "\n".join(body) + "\n", summary


def build(out_dir: Path) -> Path:
    out = Path(out_dir) / NAME
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(compute()[0])
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", type=Path, default=BUILD_DIR / "tables")
    out = build(parser.parse_args().out_dir)
    summary = compute()[1]
    print(
        f"{summary['runs']} runs; {summary['gpu_weighted_logged_hours']:.1f} GPU-weighted "
        "logged hours; all single-GPU."
    )
    print("wrote", out)


if __name__ == "__main__":
    main()
